# Generated by Django 3.2.3 on 2021-05-25 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klienci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SAP', models.IntegerField()),
                ('Nazwa', models.TextField(max_length=50)),
                ('Ulica', models.TextField(max_length=100)),
                ('Numer', models.TextField(max_length=10)),
                ('Miejscowosc', models.TextField(max_length=50)),
                ('Kodpocztowy', models.TextField(max_length=6)),
                ('Branza', models.TextField(max_length=50)),
                ('long', models.DecimalField(decimal_places=8, max_digits=11)),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('Vxx', models.TextField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Oddzialy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.TextField(max_length=50)),
                ('long', models.DecimalField(decimal_places=8, max_digits=11)),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('opis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Telefony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.TextField(max_length=50)),
                ('nazwisko', models.TextField(max_length=50)),
                ('stacjonarny', models.TextField(max_length=50)),
                ('komorkowy', models.TextField(max_length=50)),
                ('dzial', models.TextField(max_length=50)),
                ('poddzial', models.TextField(max_length=50)),
                ('stanowisko', models.TextField(max_length=50)),
                ('oddzial', models.TextField(max_length=50)),
                ('update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tugger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SAP', models.TextField(max_length=10)),
                ('Nazwa', models.TextField(max_length=50)),
                ('Data', models.DateField()),
                ('Produkt', models.TextField(max_length=50)),
                ('Kodpocztowy', models.TextField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='RealizacjeVNA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('M', 'MX-X'), ('G', 'GX-X'), ('E', 'EK-X 24/48'), ('e', 'EK-X 10'), ('J', 'JX0')], max_length=1)),
                ('wysokosc', models.CharField(choices=[('N', '0-6000'), ('S', '6000-9000'), ('W', '9000-14000'), ('B', '14000-')], max_length=1)),
                ('prowadzenie', models.CharField(choices=[('M', 'Mechaniczne'), ('I', 'Indukcyjne'), ('N', 'Swobodnie prowadzone')], max_length=1)),
                ('hamowanie', models.CharField(choices=[('M', 'Magnesy'), ('B', 'Blachy'), ('R', 'RFID'), ('O', 'Optyczne')], max_length=1)),
                ('trog', models.CharField(choices=[('S', 'Mały'), ('M', 'Średni'), ('L', 'Duży')], max_length=1)),
                ('typbaterii', models.CharField(choices=[('K', 'Kwasowo-ołowiowa'), ('C', 'Miedziane'), ('G', 'Żelowe'), ('N', 'NexSys'), ('L', 'Li-ION')], max_length=1)),
                ('navigation', models.BooleanField(verbose_name='Nawigacja')),
                ('safety', models.BooleanField(verbose_name='PSA')),
                ('safetysystem', models.BooleanField(verbose_name='GSA')),
                ('compensation', models.BooleanField(verbose_name='AFC')),
                ('devided', models.BooleanField(verbose_name='Dzielony pulpit')),
                ('tilting', models.BooleanField(verbose_name='Uchylne barierki')),
                ('atachment', models.BooleanField(verbose_name='Osprzęt na głowicy')),
                ('cold', models.BooleanField(verbose_name='Chłodnia')),
                ('reach', models.BooleanField(verbose_name='Nadwysuw')),
                ('kombi', models.BooleanField(verbose_name='Kombi')),
                ('brakes', models.BooleanField(verbose_name='Hamulce')),
                ('camera', models.BooleanField(verbose_name='Kamera')),
                ('platform', models.BooleanField(verbose_name='Platforma do wyjścia')),
                ('als', models.BooleanField(verbose_name='OS3.4 - ALS')),
                ('fleetmanager', models.BooleanField(verbose_name='FleetManager')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.klienci')),
            ],
        ),
        migrations.CreateModel(
            name='RealizacjeTugger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_seryjny', models.TextField(max_length=12)),
                ('podnoszenie', models.CharField(choices=[('E', 'Elektryczne'), ('H', 'Hydruliczne'), ('P', 'Peumatyczne')], max_length=1)),
                ('typ', models.CharField(choices=[('E', 'Typu E'), ('B', 'Typu B'), ('C', 'Typu C'), ('P', 'Typu P')], max_length=1)),
                ('wymiar', models.CharField(choices=[('E', '1200x800'), ('3', '3x800x600'), ('I', '1200x1000'), ('C', '1200x2000'), ('S', 'Specjalna')], max_length=1)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.klienci')),
            ],
        ),
        migrations.CreateModel(
            name='RealizacjeRacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('P', 'Paletowe'), ('M', 'Mobilne'), ('S', 'Shuttle'), ('A', 'Antresola'), ('D', 'Drive-In')], max_length=1)),
                ('ilosc', models.CharField(choices=[('S', '0-1000'), ('M', '1000-5000'), ('L', '5000-10000'), ('X', '10000-')], max_length=1)),
                ('_ilosc', models.PositiveIntegerField()),
                ('wysokosc', models.CharField(choices=[('N', '0-6000'), ('S', '6000-9000'), ('W', '9000-14000'), ('B', '14000-')], max_length=1)),
                ('_wysokosc', models.PositiveIntegerField()),
                ('korytarz', models.CharField(choices=[('S', 'Szeroki'), ('V', 'Wąski'), ('I', 'Inny')], max_length=1)),
                ('krata', models.BooleanField(verbose_name='Krata')),
                ('siatka', models.BooleanField(verbose_name='Siatka')),
                ('oslony', models.BooleanField(verbose_name='Ochrony')),
                ('siatka_tylna', models.BooleanField(verbose_name='Siatka tylna')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.klienci')),
            ],
        ),
        migrations.CreateModel(
            name='RealizacjeAGV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('S', 'Stacjonarna'), ('M', 'Mobilna')], max_length=1)),
                ('truck', models.CharField(choices=[('S', 'Stacjonarna'), ('M', 'Mobilna')], max_length=1)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.klienci')),
            ],
        ),
    ]
