# Generated by Django 3.2.3 on 2021-06-10 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klienci',
            name='SAP',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='realizacjeagv',
            name='klient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.klienci', to_field='SAP'),
        ),
    ]
