# Generated by Django 3.2.3 on 2021-06-11 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210610_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realizacjeracks',
            name='klient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.klienci', to_field='SAP'),
        ),
        migrations.AlterField(
            model_name='realizacjetugger',
            name='klient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.klienci', to_field='SAP'),
        ),
        migrations.AlterField(
            model_name='realizacjevna',
            name='klient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.klienci', to_field='SAP'),
        ),
    ]
