# Generated by Django 3.2.7 on 2021-09-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210912_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realizacjevna',
            name='hamowanie',
            field=models.CharField(choices=[('M', 'Magnesy'), ('B', 'Blachy'), ('R', 'RFID'), ('O', 'Optyczne'), ('N', 'Brak')], max_length=1),
        ),
    ]
