# Generated by Django 3.2.7 on 2021-09-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_realizacjevna_hamowanie'),
    ]

    operations = [
        migrations.AddField(
            model_name='realizacjeracks',
            name='zlecenie',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
