# Generated by Django 3.2.7 on 2021-09-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_realizacjeracks_zlecenie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realizacjeracks',
            name='typ',
            field=models.CharField(choices=[('P', 'Paletowe'), ('M', 'Mobilne'), ('S', 'Shuttle'), ('A', 'Antresola'), ('D', 'Drive-In'), ('W', 'W'), ('V', 'V')], max_length=1),
        ),
    ]
